-- Script de création de la table QUOTAS
-- À exécuter dans votre base de données Oracle

-- Créer la table QUOTAS si elle n'existe pas
CREATE TABLE QUOTAS (
    ID_QUOTA NUMBER PRIMARY KEY,
    TYPE_POISSON VARCHAR2(50) NOT NULL,
    VALEUR_QUOTA NUMBER(10,2) NOT NULL
);

-- Créer une séquence pour les ID (optionnel, pour auto-increment)
CREATE SEQUENCE SEQ_QUOTAS START WITH 1 INCREMENT BY 1;

-- Insérer les quotas par défaut pour les poissons
INSERT INTO QUOTAS (ID_QUOTA, TYPE_POISSON, VALEUR_QUOTA) VALUES (1, 'Sardine', 200);
INSERT INTO QUOTAS (ID_QUOTA, TYPE_POISSON, VALEUR_QUOTA) VALUES (2, 'Maquereau', 150);
INSERT INTO QUOTAS (ID_QUOTA, TYPE_POISSON, VALEUR_QUOTA) VALUES (3, 'Merlu', 180);
INSERT INTO QUOTAS (ID_QUOTA, TYPE_POISSON, VALEUR_QUOTA) VALUES (4, 'Thon', 300);
INSERT INTO QUOTAS (ID_QUOTA, TYPE_POISSON, VALEUR_QUOTA) VALUES (5, 'Loup', 120);
INSERT INTO QUOTAS (ID_QUOTA, TYPE_POISSON, VALEUR_QUOTA) VALUES (6, 'Calamar', 100);
INSERT INTO QUOTAS (ID_QUOTA, TYPE_POISSON, VALEUR_QUOTA) VALUES (7, 'Crevette', 80);
INSERT INTO QUOTAS (ID_QUOTA, TYPE_POISSON, VALEUR_QUOTA) VALUES (8, 'Rouget', 90);
INSERT INTO QUOTAS (ID_QUOTA, TYPE_POISSON, VALEUR_QUOTA) VALUES (9, 'Poulpes', 110);

COMMIT;
